version: '3.8'
networks:
  my-global-network:
    name: my-global-network
    driver: bridge
    external: true

services:
  namenode:
    build:
      context: .
      dockerfile: Dockerfile.namenode
    environment:
      - CLUSTER_NAME=test
    volumes:
      - namenode_data:/hadoop/dfs/name
      - ./core-site.xml:/etc/hadoop/core-site.xml:ro
      - ./hdfs-site.xml:/etc/hadoop/hdfs-site.xml:ro
    ports:
      - "8020:8020"
      - "9870:9870"
    networks:
      my-global-network:
        aliases:
          - namenode

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    depends_on:
      - namenode
    environment:
      - SERVICE_PRECONDITION=namenode:8020
    volumes:
      - datanode_data:/hadoop/dfs/data
      - ./core-site.xml:/etc/hadoop/core-site.xml:ro
      - ./hdfs-site.xml:/etc/hadoop/hdfs-site.xml:ro
    networks:
      - my-global-network

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    ports:
      - "8032:8032"
      - "8088:8088"
    networks:
      - my-global-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G

  nodemanager:
    build:
      context: .
      dockerfile: Dockerfile.nodemanager
    depends_on:
      - resourcemanager
    environment:
      - SERVICE_PRECONDITION=resourcemanager:8032
    networks:
      - my-global-network
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    depends_on:
      - hive-metastore-db
    environment:
      - SERVICE_PRECONDITION=hive-metastore-db:5432
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore-db:5432/metastore
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionDriverName=org.postgresql.Driver
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionUserName=hive
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionPassword=hive
    ports:
      - "9083:9083"
    networks:
      - my-global-network

  hive-metastore-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
      - POSTGRES_DB=metastore
    volumes:
      - hive_metastore_data:/var/lib/postgresql/data
    networks:
      - my-global-network

volumes:
  namenode_data:
  datanode_data:
  hive_metastore_data: