version: '3'

services:
  jenkins:
    user: root
    image: jenkins/jenkins:lts
    ports:
      - "9090:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - airflow_dags:/opt/airflow/dags  # Общий том для DAG-файлов
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - my-global-network

volumes:
  jenkins_data:
  airflow_dags:
    external: true

networks:
  my-global-network:
    external: true